export { captureTarget } from './capture.ts';
export type { CaptureOptions, CaptureResult } from './capture.ts';
export { compareImages } from './compare.ts';
export type { CompareImageInput, CompareImageResult, PixelmatchOptions } from './compare.ts';
export { buildStyleDiffs } from './diff.ts';
export type { DiffOptions } from './diff.ts';
export type { ExpectedSpec, PatchHint, StyleDiff, TokenMap } from './types/index.ts';
export { deltaE2000, rgbToLab } from './utils/color.ts';
export type { Lab } from './utils/color.ts';
export { normLineHeight, parseBoxShadow, parseCssColorToRgb, toPx } from './utils/normalize.ts';
export type { BoxShadowParsed, RGB } from './utils/normalize.ts';
